# Generated by Django 3.1.7 on 2021-05-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='finish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
