# Generated by Django 3.1.7 on 2021-05-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210503_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='finish_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
